<a href="https://colab.research.google.com/github/vr4708603-svg/2520030247_ML/blob/master/skill/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

In [ ]:
df = pd.read_csv("/content/placement_predict_50k Dataset_final (1).csv")

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (50000, 32)

Columns:
['StudentID', 'Gender', 'City', 'CollegeTier', 'Stream', 'Specialisation', 'Hostel', 'HistoryOfBacklogs', 'SGPA_Sem1', 'SGPA_Sem2', 'SGPA_Sem3', 'SGPA_Sem4', 'SGPA_Sem5', 'SGPA_Sem6', 'SGPA_Sem7', 'SGPA_Sem8', 'CGPA', 'AttendancePercent', 'Internships', 'Projects', 'Workshops', 'Certifications', 'Publications', 'AptitudeTestScore', 'SoftSkillsRating', 'CodingTestScore', 'MockInterviewScore', 'ExtraCurricular', 'CGPA_Tier', 'PlacementStatus', 'IsAnomaly', 'Salary Package']

In [ ]:
X = df.drop(columns=['PlacementStatus', 'StudentID', 'IsAnomaly'])
display(X.head())

,Gender,City,CollegeTier,Stream,Specialisation,Hostel,HistoryOfBacklogs,SGPA_Sem1,SGPA_Sem2,SGPA_Sem3,...,Workshops,Certifications,Publications,AptitudeTestScore,SoftSkillsRating,CodingTestScore,MockInterviewScore,ExtraCurricular,CGPA_Tier,Salary Package
0,Male,Ahmedabad,Tier2,ECE,Networking,No,No,6.02,6.54,6.52,...,NaN,2,0,66.7,2.2,49.4,47.8,0,Low,0.00
1,Female,Mumbai,Tier2,ECE,DataScience,Yes,Yes,5.84,5.12,5.34,...,0.0,1,0,48.2,2.4,26.7,25.8,0,Low,0.00
2,Male,Kolkata,Tier2,IT,DataScience,Yes,No,4.91,5.29,5.49,...,1.0,1,0,73.8,2.8,67.7,41.5,0,Low,3.89
3,Male,Jaipur,Tier1,CS,AI,No,No,7.67,8.03,8.08,...,1.0,2,0,69.8,2.7,66.9,48.0,0,Mid,8.37
4,Male,Pune,Tier2,IT,DataScience,Yes,No,8.14,8.97,8.36,...,NaN,4,1,73.1,2.1,71.7,61.7,1,High,18.99

In [ ]:
y = df['PlacementStatus']
display(y.head())

0    0
1    0
2    1
3    1
4    1
Name: PlacementStatus, dtype: int64

In [ ]:
features = [
    "Gender",
    "City",
    "CollegeTier",
    "Stream",
    "Specialisation",
    "Hostel",
    "HistoryOfBacklogs",

    "SGPA_Sem1",
    "SGPA_Sem2",
    "SGPA_Sem3",
    "SGPA_Sem4",
    "SGPA_Sem5",
    "SGPA_Sem6",
    "SGPA_Sem7",
    "SGPA_Sem8",

    "CGPA",
    "AttendancePercent",

    "Internships",
    "Projects",
    "Workshops",
    "Certifications",
    "Publications",

    "AptitudeTestScore",
    "SoftSkillsRating",
    "CodingTestScore",
    "MockInterviewScore",
    "ExtraCurricular"
]

X = df[features]

In [ ]:
categorical_features = [
    "Gender",
    "City",
    "CollegeTier",
    "Stream",
    "Specialisation",
    "Hostel",
    "HistoryOfBacklogs"
]

In [ ]:
numerical_features = [
    "SGPA_Sem1",
    "SGPA_Sem2",
    "SGPA_Sem3",
    "SGPA_Sem4",
    "SGPA_Sem5",
    "SGPA_Sem6",
    "SGPA_Sem7",
    "SGPA_Sem8",

    "CGPA",
    "AttendancePercent",

    "Internships",
    "Projects",
    "Workshops",
    "Certifications",
    "Publications",

    "AptitudeTestScore",
    "SoftSkillsRating",
    "CodingTestScore",
    "MockInterviewScore",
    "ExtraCurricular"
]

In [ ]:
for col in numerical_features:
    X[col] = X[col].fillna(X[col].median())

for col in categorical_features:
    X[col] = X[col].fillna(X[col].mode()[0])

/tmp/ipykernel_1012/4162187542.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].fillna(X[col].median())
/tmp/ipykernel_1012/4162187542.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].fillna(X[col].mode()[0])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),

        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore",
                drop="first"
            ),
            categorical_features
        )
    ]
)
print("Preprocessor created successfully.")

Preprocessor created successfully.

In [ ]:
logistic_model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),

        (
            "classifier",
            LogisticRegression(
                max_iter=2000,
                random_state=42
            )
        )
    ]
)
print("Logistic model pipeline created successfully.")

Logistic model pipeline created successfully.

In [ ]:
logistic_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SGPA_Sem1', 'SGPA_Sem2',
                                                   'SGPA_Sem3', 'SGPA_Sem4',
                                                   'SGPA_Sem5', 'SGPA_Sem6',
                                                   'SGPA_Sem7', 'SGPA_Sem8',
                                                   'CGPA', 'AttendancePercent',
                                                   'Internships', 'Projects',
                                                   'Workshops',
                                                   'Certifications',
                                                   'Publications',
                                                   'AptitudeTestScore',
                                                   'SoftSkillsRating',
                                                   'CodingTestScore',
                                                   'MockInterviewScore',
                                                   'ExtraCurricular']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['Gender', 'City',
                                                   'CollegeTier', 'Stream',
                                                   'Specialisation', 'Hostel',
                                                   'HistoryOfBacklogs'])])),
                ('classifier',
                 LogisticRegression(max_iter=2000, random_state=42))])

In [ ]:
y_pred = logistic_model.predict(X_test)
y_probability = logistic_model.predict_proba(X_test)[:, 1]

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("\n============================================")
print("BINOMIAL LOGISTIC REGRESSION RESULTS")
print("============================================")

print("\nAccuracy:")
print(round(accuracy, 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=["Not Placed", "Placed"]
    )
)

print("\nROC-AUC:")
print(round(roc_auc_score(y_test, y_probability), 4))

============================================
BINOMIAL LOGISTIC REGRESSION RESULTS
============================================

Accuracy:
0.9197

Confusion Matrix:
[[2926  503]
 [ 300 6271]]

Classification Report:
              precision    recall  f1-score   support

  Not Placed       0.91      0.85      0.88      3429
      Placed       0.93      0.95      0.94      6571

    accuracy                           0.92     10000
   macro avg       0.92      0.90      0.91     10000
weighted avg       0.92      0.92      0.92     10000


ROC-AUC:
0.9792